const settings = {
    RAMUH_GRID_OVERLAY_PROVIDER_URL: process.env.REACT_APP_RAMUH_GRID_OVERLAY_PROVIDER_URL,
    INITIAL_MAP_CENTER_LAT: process.env.REACT_APP_INITIAL_MAP_CENTER_LAT || 49.8,
    INITIAL_MAP_CENTER_LNG: process.env.REACT_APP_INITIAL_MAP_CENTER_LNG || 16.6,
    INITIAL_MAP_ZOOM: process.env.REACT_APP_INITIAL_MAP_ZOOM || 4,
}

export default settings